# Function Explained in detail 

In [2]:
import numpy as np

In [5]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
import torch

In [16]:
x = torch.empty(2,3)
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
Hears a code brakedown for 

In [22]:
torch.empty(2,100)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.]])

In [21]:
x = torch.empty(2,100)
n = x.shape[1]
step = torch.arange(n) [:,None] - torch.arange(n)[None,:]
print(step)

tensor([[  0,  -1,  -2,  ..., -97, -98, -99],
        [  1,   0,  -1,  ..., -96, -97, -98],
        [  2,   1,   0,  ..., -95, -96, -97],
        ...,
        [ 97,  96,  95,  ...,   0,  -1,  -2],
        [ 98,  97,  96,  ...,   1,   0,  -1],
        [ 99,  98,  97,  ...,   2,   1,   0]])


In [24]:
ones = torch.ones_like(step)
print(ones)

tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1]])


In [25]:
zeros = torch.zeros_like(step)
print(zeros)

tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]])


In [31]:
target = torch.where(step >= 0, ones, zeros)
step = torch.where (step >= 0, step, zeros)
print("Targt:",target)
print("steps:",step)

Targt: tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1]])
steps: tensor([[ 0,  0,  0,  ...,  0,  0,  0],
        [ 1,  0,  0,  ...,  0,  0,  0],
        [ 2,  1,  0,  ...,  0,  0,  0],
        ...,
        [97, 96, 95,  ...,  0,  0,  0],
        [98, 97, 96,  ...,  1,  0,  0],
        [99, 98, 97,  ...,  2,  1,  0]])


In [30]:
ratio = 0.99
discount = target * (ratio ** step)
discount

tensor([[1, 1, 1,  ..., 1, 1, 1],
        [0, 1, 1,  ..., 1, 1, 1],
        [0, 0, 1,  ..., 1, 1, 1],
        ...,
        [0, 0, 0,  ..., 1, 1, 1],
        [0, 0, 0,  ..., 0, 1, 1],
        [0, 0, 0,  ..., 0, 0, 1]])

In [ ]:
def surrogate(policy, old_probs, states, actions, rewards,discount =0.0095,
             beta = 0.01)
actions  = torch.tensor(actions, dtype=torch.int8, device=device)
rewards = torch.tensor(rewards, dtype=torch.float, device=device)
old_probs = torch.tensor()
